/**
 * Created by kyle on 9/19/17.
 */
export default (function(){
    return({
        CREATE_COURSE_SUCCESS: 'CREATE_COURSE_SUCCESS',
        UPDATE_COURSE_SUCCESS: 'UPDATE_COURSE_SUCCESS',
        SAVE_COURSE_SUCCESS: 'SAVE_COURSE_SUCCESS',
        SAVE_COURSE_FAILURE: 'SAVE_COURSE_FAILURE',
        LOAD_COURSES_SUCCESS: 'LOAD_COURSES_SUCCESS',
        LOAD_COURSES_FAILURE: 'LOAD_COURSES_FAILURE',
        LOAD_AUTHORS_SUCCESS: 'LOAD_AUTHORS_SUCCESS',
        LOAD_AUTHORS_FAILURE: 'LOAD_AUTHORS_FAILURE',
        START_AJAX_CALL:      'START_AJAX_CALL'

    });
})();
